# Generated by Django 6.0.4 on 2026-05-02 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='represented_students',
            field=models.ManyToManyField(blank=True, related_name='representatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RFID UID'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('administrativo', 'Personal Administrativo'), ('direccion', 'Dirección'), ('cafetin', 'Cafetería'), ('representante', 'Representante')], default='alumno', max_length=20, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
    ]
